"""
6_architecture.py — Architecture diagrams page for the Streamlit app.

Diagrams are NOT auto-generated on page load. The saved .mmd/.png files
in docs/diagrams/ are displayed. Click "Regenerate" to rebuild from the
live DB and codebase.

Flow:
  1. Open page → display saved PNG from docs/diagrams/ (or "not generated yet")
  2. Click Regenerate → generate Mermaid from live DB → render PNG → save to docs/diagrams/
  3. Next visit → shows the PNG saved in step 2
"""

from __future__ import annotations

import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import streamlit as st

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from app.components.sidebar import render_sidebar
from app.core.introspect import (
    generate_app_architecture_mermaid,
    generate_er_mermaid,
    generate_pipeline_mermaid,
)
from app.core.pipeline import DB_PATH, get_engine
from app.state import init_state

DIAGRAMS_DIR = Path("docs/diagrams")

_DIAGRAM_KEYS = ["ER Diagram", "Pipeline Flow", "App Architecture"]

_DESCRIPTIONS = {
    "ER Diagram": (
        "Generated from the live SQLite schema via `PRAGMA table_info` and "
        "`PRAGMA foreign_key_list`. Registry tables (`_datasets`, `_reports`) are shown "
        "first, followed by all dataset tables. All columns are shown for every table. "
        "PK and FK columns are annotated."
    ),
    "Pipeline Flow": (
        "Generated from the `_datasets` table. Node labels show real row counts and "
        "dataset names. The enrichment branch reflects diabetes-type datasets. "
        "Report item count comes from `_reports`."
    ),
    "App Architecture": (
        "Generated by introspecting `app/views/`, `app/components/`, and `app/core/` at "
        "generation time. Function counts come from the live `REGISTRY` dict and the "
        "`CHART_TYPES` list in `3_adhoc_charts.py`."
    ),
}

_MMD_FILES = {
    "ER Diagram":       DIAGRAMS_DIR / "er_diagram.mmd",
    "Pipeline Flow":    DIAGRAMS_DIR / "pipeline_flow.mmd",
    "App Architecture": DIAGRAMS_DIR / "app_architecture.mmd",
}

_PNG_FILES = {
    "ER Diagram":       DIAGRAMS_DIR / "er_diagram.png",
    "Pipeline Flow":    DIAGRAMS_DIR / "pipeline_flow.png",
    "App Architecture": DIAGRAMS_DIR / "app_architecture.png",
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _get_engine():
    try:
        return get_engine(DB_PATH)
    except Exception:
        return None


def _render_png(mermaid_src: str, mmdc: str) -> bytes | None:
    """Run mmdc on mermaid_src; return PNG bytes or None on failure."""
    with tempfile.TemporaryDirectory() as tmp:
        mmd_path = Path(tmp) / "diagram.mmd"
        png_path = Path(tmp) / "diagram.png"
        mmd_path.write_text(mermaid_src, encoding="utf-8")
        result = subprocess.run(
            [mmdc, "-i", str(mmd_path), "-o", str(png_path),
             "-w", "2400", "-H", "1800", "--scale", "2", "-b", "transparent"],
            capture_output=True,
            text=True,
            timeout=120,
        )
        if result.returncode == 0 and png_path.exists():
            return png_path.read_bytes()
    return None


def _save_to_docs(name: str, mermaid_src: str, png_bytes: bytes | None) -> None:
    DIAGRAMS_DIR.mkdir(parents=True, exist_ok=True)
    _MMD_FILES[name].write_text(mermaid_src, encoding="utf-8")
    if png_bytes is not None:
        _PNG_FILES[name].write_bytes(png_bytes)


# ---------------------------------------------------------------------------
# Page layout
# ---------------------------------------------------------------------------

render_sidebar()
engine = _get_engine()
init_state(engine)

st.title("📐 Architecture")
st.markdown(
    "Displays saved architecture diagrams. "
    "Click **Regenerate** to rebuild from the live database and codebase."
)

mmdc_bin = shutil.which("mmdc")

# ── Regenerate button ─────────────────────────────────────────────────────────
if st.button("🔄 Regenerate Diagrams", help="Rebuild all diagrams from the live DB and codebase"):
    if engine is None:
        st.error("Database not available. Import a dataset on the **Data Sources** page first.")
    else:
        saved_mmd = 0
        rendered_png = 0
        errors: list[str] = []

        with st.spinner("Generating and rendering diagrams…"):
            generators = {
                "ER Diagram":       lambda: generate_er_mermaid(engine),
                "Pipeline Flow":    lambda: generate_pipeline_mermaid(engine),
                "App Architecture": generate_app_architecture_mermaid,
            }
            for name, gen_fn in generators.items():
                try:
                    src = gen_fn()
                except Exception as exc:
                    errors.append(f"{name}: generation failed — {exc}")
                    continue

                png_bytes: bytes | None = None
                if mmdc_bin:
                    png_bytes = _render_png(src, mmdc_bin)
                    if png_bytes:
                        rendered_png += 1
                    else:
                        errors.append(f"{name}: mmdc failed to render PNG")

                _save_to_docs(name, src, png_bytes)
                saved_mmd += 1

        parts = [f"Generated {saved_mmd} diagram(s)"]
        if rendered_png:
            parts.append(f"rendered {rendered_png} PNG(s)")
        parts.append("saved to docs/diagrams/")
        st.success(" · ".join(parts))
        if not mmdc_bin:
            st.info(
                "Install Mermaid CLI for PNG rendering: "
                "`npm install -g @mermaid-js/mermaid-cli`"
            )
        for err in errors:
            st.warning(err)
        st.rerun()

# ── Diagram selector ──────────────────────────────────────────────────────────
selected = st.radio(
    "Select diagram",
    options=_DIAGRAM_KEYS,
    horizontal=True,
)

png_path = _PNG_FILES[selected]
mmd_path = _MMD_FILES[selected]

st.divider()

# ── Display saved PNG (or .mmd source if no PNG) ─────────────────────────────
if png_path.exists():
    png_bytes = png_path.read_bytes()
    st.image(png_bytes, caption=selected, use_container_width=True)
    st.download_button(
        label=f"Download {selected} PNG",
        data=png_bytes,
        file_name=png_path.name,
        mime="image/png",
    )
elif mmd_path.exists():
    st.info("PNG not rendered — showing Mermaid source. Install `mmdc` and click Regenerate for PNG.")
    st.code(mmd_path.read_text(encoding="utf-8"), language="text")
else:
    st.info("No diagrams generated yet. Click **🔄 Regenerate Diagrams** above.")

# ── Description ───────────────────────────────────────────────────────────────
with st.expander("Description", expanded=True):
    st.markdown(_DESCRIPTIONS[selected])

# ── Mermaid source ────────────────────────────────────────────────────────────
if mmd_path.exists():
    with st.expander("View / Copy Mermaid Source", expanded=False):
        mmd_content = mmd_path.read_text(encoding="utf-8")
        st.code(mmd_content, language="text")
        st.download_button(
            label="Download .mmd source",
            data=mmd_content.encode("utf-8"),
            file_name=mmd_path.name,
            mime="text/plain",
            key="dl_mmd",
        )
