"""
6_architecture.py — Architecture diagrams page for the Streamlit app.

Features:
- Diagrams are generated live from the actual DB schema and codebase
- Radio: ER Diagram | Pipeline Flow | App Architecture
- Renders PNG via mmdc if available, otherwise shows Mermaid source
- "Regenerate" button refreshes from DB/code and saves .mmd + .png to docs/diagrams/
- Download buttons for both PNG and .mmd source
"""

from __future__ import annotations

import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import streamlit as st

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from app.components.sidebar import render_sidebar
from app.core.introspect import (
    generate_app_architecture_mermaid,
    generate_er_mermaid,
    generate_pipeline_mermaid,
)
from app.core.pipeline import DB_PATH, get_engine
from app.state import init_state

DIAGRAMS_DIR = Path("docs/diagrams")

_DIAGRAM_KEYS = ["ER Diagram", "Pipeline Flow", "App Architecture"]

_DESCRIPTIONS = {
    "ER Diagram": (
        "Generated live from the actual SQLite schema via `PRAGMA table_info` and "
        "`PRAGMA foreign_key_list`. Registry tables (`_datasets`, `_reports`) are shown "
        "at the top. Dataset tables (`ds_*`) reflect every CSV imported through the app. "
        "Tables with more than 15 columns are truncated — PK and FK columns are always shown."
    ),
    "Pipeline Flow": (
        "Generated live from the `_datasets` table. Node labels show real row counts and "
        "dataset names. The enrichment branch is shown only when diabetes-type datasets are "
        "present. Report item count comes from `_reports`."
    ),
    "App Architecture": (
        "Generated by introspecting `app/views/`, `app/components/`, and `app/core/` at "
        "page-load time. Function counts come from the live `REGISTRY` dict and the "
        "`CHART_TYPES` list in `3_adhoc_charts.py`."
    ),
}

_MMD_FILES = {
    "ER Diagram":        DIAGRAMS_DIR / "er_diagram.mmd",
    "Pipeline Flow":     DIAGRAMS_DIR / "pipeline_flow.mmd",
    "App Architecture":  DIAGRAMS_DIR / "app_architecture.mmd",
}

_PNG_FILES = {
    "ER Diagram":        DIAGRAMS_DIR / "er_diagram.png",
    "Pipeline Flow":     DIAGRAMS_DIR / "pipeline_flow.png",
    "App Architecture":  DIAGRAMS_DIR / "app_architecture.png",
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _get_engine():
    try:
        return get_engine(DB_PATH)
    except Exception:
        return None


def _generate_all(engine) -> dict[str, str]:
    """Return fresh Mermaid source for all three diagrams."""
    sources: dict[str, str] = {}
    if engine is not None:
        sources["ER Diagram"] = generate_er_mermaid(engine)
        sources["Pipeline Flow"] = generate_pipeline_mermaid(engine)
    else:
        sources["ER Diagram"] = "erDiagram\n    %% Database not available"
        sources["Pipeline Flow"] = "flowchart TD\n    DB[Database not available]"
    sources["App Architecture"] = generate_app_architecture_mermaid()
    return sources


def _render_png(mermaid_src: str, mmdc: str) -> bytes | None:
    """Run mmdc on mermaid_src; return PNG bytes or None on failure."""
    with tempfile.TemporaryDirectory() as tmp:
        mmd_path = Path(tmp) / "diagram.mmd"
        png_path = Path(tmp) / "diagram.png"
        mmd_path.write_text(mermaid_src, encoding="utf-8")
        result = subprocess.run(
            [mmdc, "-i", str(mmd_path), "-o", str(png_path), "-w", "1400"],
            capture_output=True,
            text=True,
            timeout=30,
        )
        if result.returncode == 0 and png_path.exists():
            return png_path.read_bytes()
    return None


def _save_to_docs(name: str, mermaid_src: str, png_bytes: bytes | None) -> None:
    """Persist generated .mmd (and optionally .png) to docs/diagrams/."""
    DIAGRAMS_DIR.mkdir(parents=True, exist_ok=True)
    _MMD_FILES[name].write_text(mermaid_src, encoding="utf-8")
    if png_bytes is not None:
        _PNG_FILES[name].write_bytes(png_bytes)


# ---------------------------------------------------------------------------
# Page layout
# ---------------------------------------------------------------------------

render_sidebar()
engine = _get_engine()
init_state(engine)

st.title("📐 Architecture")
st.markdown(
    "Diagrams are **generated live** from the actual database schema and codebase. "
    "Click **Regenerate** to refresh after importing new datasets or changing the code."
)

# ── Cached diagram source in session state ────────────────────────────────────
if "arch_diagrams" not in st.session_state:
    with st.spinner("Generating diagrams…"):
        st.session_state["arch_diagrams"] = _generate_all(engine)

sources: dict[str, str] = st.session_state["arch_diagrams"]

# ── Regenerate button ─────────────────────────────────────────────────────────
mmdc_bin = shutil.which("mmdc")

if st.button("🔄 Regenerate Diagrams", help="Rebuild diagrams from the live DB and codebase"):
    with st.spinner("Regenerating…"):
        sources = _generate_all(engine)
        st.session_state["arch_diagrams"] = sources

        saved_mmd = 0
        rendered_png = 0
        errors: list[str] = []

        for name, src in sources.items():
            png_bytes: bytes | None = None
            if mmdc_bin:
                png_bytes = _render_png(src, mmdc_bin)
                if png_bytes:
                    rendered_png += 1
                else:
                    errors.append(f"{name}: mmdc failed to render PNG")
            _save_to_docs(name, src, png_bytes)
            saved_mmd += 1

    parts = [f"Regenerated {saved_mmd} diagram(s)"]
    if rendered_png:
        parts.append(f"rendered {rendered_png} PNG(s)")
    parts.append("saved .mmd to docs/diagrams/")
    st.success(" · ".join(parts))
    if not mmdc_bin:
        st.info(
            "Install Mermaid CLI for PNG rendering: "
            "`npm install -g @mermaid-js/mermaid-cli`"
        )
    for err in errors:
        st.warning(err)
    st.rerun()

# ── Diagram selector ──────────────────────────────────────────────────────────
selected = st.radio(
    "Select diagram",
    options=_DIAGRAM_KEYS,
    horizontal=True,
)

mermaid_src = sources.get(selected, "")
png_path = _PNG_FILES[selected]
mmd_path = _MMD_FILES[selected]

st.divider()

# ── Render / display ──────────────────────────────────────────────────────────
png_bytes: bytes | None = None

if mmdc_bin:
    with st.spinner("Rendering…"):
        png_bytes = _render_png(mermaid_src, mmdc_bin)

if png_bytes:
    st.image(png_bytes, caption=selected, use_container_width=True)
    st.download_button(
        label=f"Download {selected} PNG",
        data=png_bytes,
        file_name=png_path.name,
        mime="image/png",
    )
elif png_path.exists():
    # Fall back to the last saved PNG from docs/diagrams/
    saved_png = png_path.read_bytes()
    st.image(saved_png, caption=f"{selected} (last saved)", use_container_width=True)
    st.download_button(
        label=f"Download {selected} PNG (last saved)",
        data=saved_png,
        file_name=png_path.name,
        mime="image/png",
    )
else:
    st.info(
        "Install Mermaid CLI to render PNG: "
        "`npm install -g @mermaid-js/mermaid-cli`"
    )

# ── Description ───────────────────────────────────────────────────────────────
with st.expander("Description", expanded=True):
    st.markdown(_DESCRIPTIONS[selected])

# ── Mermaid source ────────────────────────────────────────────────────────────
with st.expander("View / Copy Mermaid Source", expanded=False):
    st.code(mermaid_src, language="text")
    st.download_button(
        label="Download .mmd source",
        data=mermaid_src.encode("utf-8"),
        file_name=mmd_path.name,
        mime="text/plain",
        key="dl_mmd",
    )
